version: '3.8'
services:
    db:
        image: postgres:17
        restart: always
        environment:
            POSTGRES_DB: quickpay
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres@123!
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
